version: '3.9'

networks:
  cunetwork:
    name: cunetwork
    
services:
    e2e-tests:
        image: e2e-tests
        container_name: e2e-tests
        build:
            context: .
            dockerfile: test/e2e/ContosoUniversity.AcceptanceTests/Dockerfile
            target: test/e2e
        # environment:
        #     ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}
        entrypoint: "dotnet test --no-build --verbosity normal"
        networks:
        - cunetwork
