networks:
  cunetwork:
    name: cunetwork

volumes:
  sqlvolume:
    name: sqlvolume

services:
  web:
    image: cuweb
    container_name: cuweb
    hostname: web
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: src/ContosoUniversity.Mvc/Dockerfile
    networks:
      - cunetwork

  courses-api:
    image: courses-api
    container_name: courses-api
    hostname: courses-api
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: src/Courses.Api/Dockerfile
    networks:
      - cunetwork

  departments-api:
    image: departments-api
    container_name: departments-api
    hostname: departments-api
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: src/Departments.Api/Dockerfile
    networks:
      - cunetwork

  students-api:
    image: students-api
    container_name: students-api
    hostname: students-api
    depends_on:
      - "db"
    build:
      context: .
      dockerfile: src/Students.Api/Dockerfile
    networks:
      - cunetwork

  db:
    image: mcr.microsoft.com/mssql/server
    container_name: cudb
    hostname: db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: <YourStrong!Passw0rd>
    ports:
      - "1433:1433"
    networks:
      - cunetwork
