name: Pull Request Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_unit_testing:
    name: Build and Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Solution
      run: dotnet build --no-restore
      
    - name: Run Unit Tests
      working-directory: test/unit/ContosoUniversity.Domain.Tests
      run: dotnet test --no-build --verbosity normal
      
  integration_testing:
    name: Integration Testing
    runs-on: ubuntu-latest
    # container:
    #   image: mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    # - name: Create docker network
    #   run: docker network inspect cunetwork >/dev/null 2>&1 || \docker network create cunetwork
      # run: |
      #   docker network ls
      #   docker network inspect cunetwork

    - name: Run Docker Infrastructure
      run: docker compose up -d --build --network cunetwork
      # options:
      #   --network cunetwork
      
    - name: Init database
      run: docker run --rm --entrypoint /opt/mssql-tools/bin/sqlcmd --workdir /scripts --volume "$(pwd)"/database:/scripts --network=cunetwork mcr.microsoft.com/mssql-tools -S cudb -U SA -P "<YourStrong!Passw0rd>" -i "db-init.sql"
      
    - name: Get the container IP address
      run: CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' cuweb)
    
    - name: Test host availability
      run: curl https://${CONTAINER_IP}:10001/Courses

    # - name: Run Docker E2E Tests
    #   run: docker compose -f docker-compose-tests.yml up --exit-code-from e2e-tests e2e-tests
    
    # - name: Run Integration Tests
    #   run: dotnet test --no-build --verbosity normal test/integration/ContosoUniversity.Mvc.IntegrationTests/ContosoUniversity.Mvc.IntegrationTests.csproj

    # - name: Run Playwright
    #   run: docker run -it --rm --ipc=host mcr.microsoft.com/playwright/dotnet:v1.40.0-jammy /bin/bash
      
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v3
    #   with:
    #     dotnet-version: 6.0.x
        
    # - name: Build E2E Tests
    #   working-directory: test/e2e/ContosoUniversity.AcceptanceTests
    #   run: |
    #     dotnet restore
    #     dotnet build --no-restore

    # - name: Ensure browsers are installed
    #   run: pwsh test/e2e/ContosoUniversity.AcceptanceTests/bin/Debug/net6.0/playwright.ps1 install --with-deps
        
    # - name: Run E2E Tests
    #   working-directory: test/e2e/ContosoUniversity.AcceptanceTests
    #   run: dotnet test --no-build --verbosity normal

    - name: Shutdown Docker Infrastructure
      run: docker compose down
